micronaut:
  application:
    name: message-pipeline
  server:
    port: 8080
    cors:
      enabled: true
      configurations:
        ui:
          allowed-origins:
            - http://localhost:63342
  executors:
    messageProcessor:
      type: fixed
      nThreads: 4
      maxPoolSize: 4
    pipelineWorker:
      type: fixed
      nThreads: 4
      maxPoolSize: 4

sqlite:
  db-path: /Users/IN45626365/Desktop/Workspace/CustomProjects/provider/message_store.db
  maxMessages: 1000000
  maxStorageSize: 1073741824  # 1GB
  retentionPeriodMs: 86400000 # 24 hours
  maxPoolSize: 10
  connectionTimeout: 30000
  compressionEnabled: true

rsocket:
  port: 7000
  transport: TCP
  maxInboundPayloadSize: 1048576 # 1MB

pipeline:
  queue:
    maxQueueSizeBytes: 2048576  # 1MB
    initialQueueCapacity: 100000
    enforceByteLimit: false
    maxMessagesPerConsumer: 1000000
    memoryThresholdPercentage: 0.8
    minimumFreeMemoryBytes: 104857600 # 100MB
  maxConcurrentMessages: 10000
  maxQueueSize: 10000
  processingTimeoutMs: 10000
  maxRetryAttempts: 1000000
  retryDelayMs: 1000
  manager:
    queueCapacity: 10000
    threadPoolSize: 10
    maxpollSize: 10
    corePoolSize: 4
    keepAliveTime: 1000


parallel-processing:
  parallelThreads: 4
  queueSizePerThread: 25
  maxBatchSize: 100
  minBatchSize: 1
  batchTimeoutMs: 5000
  maxBatchRetries: 3
  maintainOrderWithinBatch: true
rocks:
  storage:
    db-path: /Users/IN45626365/Desktop/Workspace/CustomProjects/provider/rocksdb
    max-storage-size: ${ROCKS_MAX_STORAGE:1073741824}  # 1GB
    compression: true
    compression-type: LZ4
    enable-wal: true

  performance:
    write-buffer-size: 67108864  # 64MB
    max-write-buffer-number: 3
    max-background-compactions: 4
    block-cache-size: 33554432  # 32MB
    block-size: 16384  # 16KB
    verify-checksums: true

  tuning:
    target-file-size-base: 67108864  # 64MB
    max-bytes-for-level-base: 268435456  # 256MB
    num-levels: 7
    level-multiplier: 10

  maintenance:
    cleanup-interval-hours: 1
    cleanup-batch-size: 1000
    auto-compaction: true
    max-compaction-threads: 2
messaging:
  max:
    message:
      size: 2097152
compression:
  threshold:
    bytes: 524288
  buffer:
    size: 32768

message:
  store:
    batch-size: 20
  dlq:
    storage:
      path: /Users/IN45626365/Desktop/Workspace/CustomProjects/provider
  offset:
    storage:
      path: /Users/IN45626365/Desktop/Workspace/CustomProjects/provider
  dispatch:
    polling-interval-ms: 100
dispatch:
  schedule:
    processInterval: 1000
    cleanupInterval: 30000
    batchTimeoutMs: 30000