micronaut:
  application:
    name: message-pipeline
  server:
    port: 8080
  executors:
    messageProcessor:
      type: fixed
      nThreads: 4
      maxPoolSize: 4
    pipelineWorker:
      type: fixed
      nThreads: 4
      maxPoolSize: 4

sqlite:
  db-path: /Users/anuragmishra/Desktop/workspace/messaging/aqeduct-provider/message_store.db
  maxMessages: 1000000
  maxStorageSize: 1073741824  # 1GB
  retentionPeriodMs: 86400000 # 24 hours
  maxPoolSize: 10
  connectionTimeout: 30000
  compressionEnabled: true

rsocket:
  port: 7000
  transport: TCP
  maxInboundPayloadSize: 1048576 # 1MB

pipeline:
  queue:
    max-queue-size-bytes: 1048576  # 1MB
    initial-queue-capacity: 1000
    enforce-byte-limit: true
    max-messages-per-consumer: 10000
    memory-threshold-percentage: 0.8
    minimum-free-memory-bytes: 104857600  # 100MB
  maxConcurrentMessages: 100
  maxQueueSize: 1000
  processingTimeoutMs: 10000
  maxRetryAttempts: 3
  retryDelayMs: 1000
  manager:
    queueCapacity: 1000
    threadPoolSize: 4

parallel-processing:
  parallelThreads: 4
  queueSizePerThread: 25
  maxBatchSize: 100
  minBatchSize: 1
  batchTimeoutMs: 5000
  maxBatchRetries: 3
  maintainOrderWithinBatch: true
rocks:
  storage:
    db-path: /Users/anuragmishra/Desktop/workspace/messaging/aqeduct-provider/rocksdb
    max-storage-size: ${ROCKS_MAX_STORAGE:1073741824}  # 1GB
    compression: true
    compression-type: LZ4
    enable-wal: true

  performance:
    write-buffer-size: 67108864  # 64MB
    max-write-buffer-number: 3
    max-background-compactions: 4
    block-cache-size: 33554432  # 32MB
    block-size: 16384  # 16KB
    verify-checksums: true

  tuning:
    target-file-size-base: 67108864  # 64MB
    max-bytes-for-level-base: 268435456  # 256MB
    num-levels: 7
    level-multiplier: 10

  maintenance:
    cleanup-interval-hours: 1
    cleanup-batch-size: 1000
    auto-compaction: true
    max-compaction-threads: 2
